services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis
    hostname : postgis.local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
     - "5432:5432"
    volumes:
     - ./postgis_data:/var/lib/postgresql/data
     - ./common/ddl:/docker-entrypoint-initdb.d

  airway-design:
    image: airway-design-prod:latest
    command: ["java", "-jar", "/app/app.war"]
    depends_on:
      - db
    ports:
      - "8081:8080"  
      - "48081:48080"
